### ISSUE TITLE
Move documentation into GitHub wiki

### ISSUE THREAD

**Issue by obbardc** [64studio/pdk#21]
Files in the repo under `docs/` and `manual/` should be moved into the Wiki. Should we also update and remove some documentation for the next release? Maybe it would be a good idea to start the documentation from scratch using these files as a reference.

**Comment by obbardc** [comment]
I have begun moving the documentation into the GitHub wiki. All of the markdown in the `manual` folder is now in the wiki. I think the documentation in the `doc` folder is possibly a bit out of date, and not in the right markdown format, so I have left it out, for now.

**Comment by danielhjames** [comment]
Thanks!

**Comment by obbardc** [comment]
Superseded by #36.
