### ISSUE TITLE
Is there a way to generate a repo with multiple suites in it?

### ISSUE THREAD

**Issue by obbardc** [64studio/pdk#25]
As the question asks.

This is more of a way for me to keep track of ideas I am having...

**Comment by danielhjames** [comment]
Yes, please see an example at http://apt.sourcefabric.org/dists/ which is built with reprepro. For a package which does not contain any binaries, the path to the *all.deb might be the same in every Packages file across the different suites, for example the second entry on http://apt.sourcefabric.org/dists/jessie/main/binary-amd64/Packages

Binary packages built against certain library versions in a particular suite can be given a suite suffix to help identify them, for example booktype_2.0.0~jessie-1_all.deb

You can even have multiple dists per suite if you use unique codenames, see the second answer to http://askubuntu.com/questions/252047/how-do-i-setup-multiple-suites-in-reprepro

**Comment by obbardc** [comment]
Right, but I want to do this with the `pdk repogen` command.

With my `picax.xml` file looking like the following, I can get `pdk repogen picax.xml` to give me an APT repo with the suite `testing` in it.

I'm just wondering if I can get the commands to make more than one suite with no additional fuss or other software.

The `pdk repogen` command will remove the target directory.

```
<component>
  <id>testing</id>
  <meta>
    <apt-deb.key>apt@64studio.com</apt-deb.key>
  </meta>
  <contents>
    <component>core.xml</component>
  </contents>
</component>
```

**Comment by obbardc** [comment]
Reprepro does a better job than PDK for this.
