### ISSUE TITLE
How to share a cache between multiple projects?

### ISSUE THREAD

**Issue by obbardc** [64studio/pdk#28]
We know it can be done, but how?

This would be a great way to save (precious!) disk space.

I'll let you figure this one out Daniel since you have done it in the past. Holla if you need access to a Debian server running the latest PDK source.

**Comment by danielhjames** [comment]
For projects derived from the same base distro, the way we did this in the past was simply to create a symlink from the project cache directory to the shared cache directory. It does save a lot of disk space that way.
