### ISSUE TITLE
Unknown error code

### ISSUE THREAD

**Issue by dschoonover** [64studio/pdk#30]
Ive tried intalling the pdk package and I return an unknown error code. Ive also tried running the scripts in python 2.7 on a barebones debian system.  But i keep gettin ... then i cannot continue to run python scripts. Ive also unziped the .gz and put the file path into the source list after running apt-get install i return 

The package lists or status file could not be parsed or opened.

I try sudo apt-get install pdk and I return 

Unable to locate package pdk

Ive also tried with the all.deb files.

**Comment by danielhjames** [comment]
Hi, the message `The package lists or status file could not be parsed or opened` suggests your `/etc/apt/sources.list` file, or a file in `/etc/apt/sources.list.d/` or perhaps the file `/var/lib/dpkg/status` has a syntax error.

The reason why `sudo apt-get install pdk` does not work is that we don't have an apt repo set up offering this package. The .deb file can be installed with `sudo apt-get install gdebi; sudo gdebi pdk_1.0.0_all.deb` which will resolve dependencies for you, once you have fixed the problem with your system above.

**Comment by dschoonover** [comment]
Hi ive cleared the 
Ect/apt/sources.list
To orginal state.

When I run 
sudo apt-get install gdebi; sudo gdebi pdk_1.0.0_all.deb
I return 
Gdeb error, file not found

Ive moved the file to the home directory 
Ran cd /home
I still return Gdeb error, file not found 


I  read about 64bit and 32bit compatibility.

I ran

Sudo Dpkg --add architecture i386
Then
Sudo apt-get update
Then
Sudo apt-get install libc6: i386 zlib1g: i386 ...
Then
Sudo apt-get upgrade 
Sudo apt-get update
Then
Sudo gdebi pdk_1.0.0_all.deb

PDK is now installed.

**Comment by obbardc** [comment]
We should setup an apt repository for version 1.0 unstable testing. I like the idea of https://packagecloud.io/, but I am always weary of cloud stuff.

Daniel, can you look into the best way of us doing this? A neat way would be an auto-deb-generator which updates the repository on every Git commit ;-). This would also be very useful for our other projects.

**Comment by obbardc** [comment]
Tutorial on how to use coming soon, see #36
