### ISSUE TITLE
heads up: related work

### ISSUE THREAD

**Issue by magnetophon** [64studio/pdk#32]
As a former very content 64studio user, I'd like to say thank you!

Currently, I'm using [NixOS](https://nixos.org) with [Musnix](https://github.com/musnix/musnix), for some of the same reasons you created pdk and 64studio:
I can develop the perfect real time audio workstation, and do it under version control.

Some more reasons NixOS is good [for musicians](https://github.com/musnix/musnix/wiki/NixOS-for-Musicians).

**Comment by danielhjames** [comment]
Hi Bart, you're very welcome :-) Good to see there is still innovation in distro design!
