### ISSUE TITLE
Packages for Debian Stretch, Buster & Sid

### ISSUE THREAD

**Issue by obbardc** [64studio/pdk#33]
As Debian Stretch is now stable, buster and sid are developing, we need to begin to build development packages.

**Comment by obbardc** [comment]
Good news; the packages build for `amd64` on stretch, buster and sid. There are some warnings, mainly due to the debhelper compatibility level.

Next step will be to test functionality on each system, see what's broken! I don't think it will be much, since the python code is fairly portable.

**Comment by danielhjames** [comment]
Thanks Chris, I've updated compat to 9.

**Comment by obbardc** [comment]
I have made some debs available for Debian Stretch.
